server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # HAProxy / reverse proxies
    absolute_redirect off;

    gzip on;
    gzip_types text/css application/javascript application/json application/octet-stream;

    location = /firmware/plane-radar.bin {
        default_type application/octet-stream;
        add_header Content-Disposition 'attachment; filename="plane-radar.bin"';
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }

    location /firmware/ {
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }

    location / {
        add_header Cache-Control "no-cache";
        try_files $uri $uri/ /index.html;
    }
}
